[workspace]
resolver = "2"
members = [
    "crates/protocol",
    "crates/geometry",
    "crates/session-api",
    "crates/fake-skyrim",
    "crates/host",
]

[workspace.package]
edition = "2024"
version = "0.0.1"

[workspace.dependencies]
skycraft-skate-protocol = { path = "crates/protocol" }
skycraft-skate-geometry = { path = "crates/geometry" }
skycraft-skate-session-api = { path = "crates/session-api" }
