//! Adapter from the pinned IW4L Skate session to SkyCraft's stable session API.
//!
//! This crate contains no Skate 3 retail data. Construction succeeds at runtime
//! only when the caller supplies a locally prepared data root from their own copy.

use skate_host::bridge::{InputFrame, PreparedCollision, Session};
use skycraft_skate_session_api as api;
use std::{
    path::{Path, PathBuf},
    sync::mpsc,
    thread,
    time::Duration,
};

pub struct RealSkateSession {
    data_root: PathBuf,
    session: Option<Session>,
    pending_world: Option<api::WorldGeometry>,
    installed_revision: u64,
    requested_revision: u64,
    build_send: Option<mpsc::Sender<api::WorldGeometry>>,
    built_receive: Option<mpsc::Receiver<(u64, Result<PreparedCollision, String>)>>,
    accumulated: f32,
}

impl RealSkateSession {
    /// Accept either the converter's output folder or its nested `assets` folder,
    /// and verify the stable minimum contract before the heavy Session load begins.
    pub fn resolve_data_root(path: &Path) -> Result<PathBuf, String> {
        let candidates = [path.to_path_buf(), path.join("assets")];
        let required = [
            "private/skater.glb",
            "private/game.json",
            "private/stock/physics-skeletons.json",
            "private/stock/skater-collections.json",
            "private/stock/data/config/input.cfg",
        ];
        for candidate in candidates {
            if required.iter().all(|relative| candidate.join(relative).is_file()) {
                return Ok(candidate);
            }
        }
        Err(format!(
            "prepared Skate data is incomplete at {} (expected private/game.json, skater.glb, stock physics/collections, and stock input.cfg; point SKYRIM_SKATE_DATA at the converter output or its assets folder)",
            path.display()
        ))
    }

    pub fn new(data_root: PathBuf) -> Self {
        Self {
            data_root,
            session: None,
            pending_world: None,
            installed_revision: 0,
            requested_revision: 0,
            build_send: None,
            built_receive: None,
            accumulated: 0.0,
        }
    }

    pub fn preload(&self) -> Result<(), String> {
        Session::preload(&self.data_root)
    }

    fn convert_pose(pose: skate_host::bridge::Pose) -> api::SessionPose {
        let bones = pose
            .names
            .iter()
            .zip(pose.bones.iter())
            .take(api::MAX_BONES)
            .map(|(name, matrix)| api::BoneTransform {
                name_hash: api::fnv1a64(name),
                matrix: matrix.to_cols_array(),
            })
            .collect();

        let camera = pose.camera.map(|(position, basis, fov_deg)| api::CameraPose {
            position: position.to_array(),
            forward: basis.z_axis.to_array(),
            up: basis.y_axis.to_array(),
            fov_deg,
        });

        api::SessionPose {
            root: pose.root.to_cols_array(),
            bones,
            camera,
            velocity: pose.velocity.to_array(),
            tick: pose.tick,
            state_code: api::fnv1a64(&pose.state) as u32,
        }
    }

    fn input_frame(input: api::ControllerFrame) -> InputFrame {
        InputFrame::from_pad(
            input.buttons,
            input.triggers,
            input.left,
            input.right,
            input.packet,
        )
    }

    /// Revisions are generated by the host with wrapping_add(1). Treat them as
    /// serial numbers so a delayed older world cannot replace a newer request,
    /// while still handling the practically unreachable u64 wrap correctly.
    fn revision_is_newer(candidate: u64, current: u64) -> bool {
        let distance = candidate.wrapping_sub(current);
        distance != 0 && distance < (1_u64 << 63)
    }

    fn ensure_collision_worker(&mut self) -> Result<(), String> {
        if self.build_send.is_some() {
            return Ok(());
        }
        let session = self
            .session
            .as_ref()
            .ok_or("cannot start collision worker before Skate session exists")?;
        let builder = session.collision_builder();
        let (send, jobs) = mpsc::channel::<api::WorldGeometry>();
        let (built_send, built_receive) =
            mpsc::channel::<(u64, Result<PreparedCollision, String>)>();

        thread::Builder::new()
            .name("skyrim-skate-collision".into())
            .spawn(move || {
                while let Ok(mut world) = jobs.recv() {
                    // Collapse queued world revisions so walking through Skyrim does
                    // not make the collision worker build obsolete intermediate sets.
                    while let Ok(newer) = jobs.try_recv() {
                        world = newer;
                    }
                    let revision = world.revision;
                    let result = builder.build(world.triangles, world.rails);
                    if built_send.send((revision, result)).is_err() {
                        break;
                    }
                }
            })
            .map_err(|error| format!("could not start Skate collision worker: {error}"))?;

        self.build_send = Some(send);
        self.built_receive = Some(built_receive);
        Ok(())
    }

    fn wait_for_requested_collision(&mut self) -> Result<(), String> {
        if self.requested_revision == self.installed_revision {
            return Ok(());
        }
        let receive = self
            .built_receive
            .as_ref()
            .ok_or("Skate collision worker receiver missing during activation")?;

        while self.installed_revision != self.requested_revision {
            let (revision, prepared) = receive
                .recv_timeout(Duration::from_secs(30))
                .map_err(|error| match error {
                    mpsc::RecvTimeoutError::Timeout => format!(
                        "timed out preparing Skate collision revision {}",
                        self.requested_revision
                    ),
                    mpsc::RecvTimeoutError::Disconnected => {
                        "Skate collision worker disconnected during activation".to_string()
                    }
                })?;
            let prepared = prepared?;
            let session = self
                .session
                .as_mut()
                .ok_or("Skate session disappeared before collision install")?;
            session.install_collision(prepared)?;
            self.installed_revision = revision;
        }
        Ok(())
    }

    fn install_prepared_collision(&mut self) -> Result<(), String> {
        let Some(receive) = self.built_receive.as_ref() else {
            return Ok(());
        };

        let mut newest = None;
        loop {
            match receive.try_recv() {
                Ok(result) => newest = Some(result),
                Err(mpsc::TryRecvError::Empty) => break,
                Err(mpsc::TryRecvError::Disconnected) => {
                    return Err("Skate collision worker disconnected".into());
                }
            }
        }

        let Some((revision, prepared)) = newest else {
            return Ok(());
        };
        let prepared = prepared?;
        let session = self
            .session
            .as_mut()
            .ok_or("Skate session disappeared before collision install")?;
        session.install_collision(prepared)?;
        self.installed_revision = revision;
        Ok(())
    }
}

impl api::SessionBackend for RealSkateSession {
    fn install_world(&mut self, world: api::WorldGeometry) -> Result<(), String> {
        if world.revision == self.installed_revision || world.revision == self.requested_revision {
            return Ok(());
        }

        // IPC/world preparation is asynchronous. Never let a delayed snapshot
        // move the desired collision world backwards after a newer revision was
        // already accepted.
        if self.requested_revision != self.installed_revision
            && !Self::revision_is_newer(world.revision, self.requested_revision)
        {
            return Ok(());
        }
        if self.requested_revision == self.installed_revision
            && self.installed_revision != 0
            && !Self::revision_is_newer(world.revision, self.installed_revision)
        {
            return Ok(());
        }

        if self.session.is_none() {
            self.requested_revision = world.revision;
            self.pending_world = Some(world);
            return Ok(());
        }

        self.ensure_collision_worker()?;
        self.requested_revision = world.revision;
        self.build_send
            .as_ref()
            .ok_or("Skate collision worker sender missing")?
            .send(world)
            .map_err(|_| "Skate collision worker disconnected".to_string())
    }

    fn activate(
        &mut self,
        spawn: [f32; 3],
        heading_radians: f32,
        aspect_ratio: f32,
    ) -> Result<api::SessionPose, String> {
        if self.session.is_none() {
            let world = self
                .pending_world
                .take()
                .ok_or("real Skate session has no installed collision world")?;
            let revision = world.revision;
            let mut session = Session::new(
                &self.data_root,
                world.triangles,
                world.rails,
                spawn,
                heading_radians,
            )?;
            session.set_aspect_ratio(aspect_ratio);
            self.installed_revision = revision;
            self.requested_revision = revision;
            self.session = Some(session);
            self.ensure_collision_worker()?;
        }

        // If this is a retained Session being reactivated after a Skyrim
        // world/epoch change, do not start it on the previous world's collision.
        // Heartbeat runs independently, so waiting here cannot look like host death.
        self.wait_for_requested_collision()?;
        self.install_prepared_collision()?;
        let session = self.session.as_mut().expect("session initialized above");
        session.set_aspect_ratio(aspect_ratio);
        self.accumulated = 0.0;
        let pose = Self::convert_pose(session.activate(spawn, heading_radians)?);
        if !pose.finite() {
            return Err("real Skate session returned a non-finite activation pose".into());
        }
        Ok(pose)
    }

    fn step(
        &mut self,
        input: api::ControllerFrame,
        frame_seconds: f32,
        aspect_ratio: f32,
    ) -> Result<api::SessionPose, String> {
        self.install_prepared_collision()?;
        let session = self
            .session
            .as_mut()
            .ok_or("real Skate session is not activated")?;

        session.set_aspect_ratio(aspect_ratio);
        let dt = frame_seconds.clamp(0.0, 0.1);
        session.collect(Self::input_frame(input), dt);
        self.accumulated = (self.accumulated + dt).min(0.15);

        while self.accumulated >= session.period() {
            self.accumulated -= session.period();
            session.advance()?;
        }

        let pose = Self::convert_pose(session.pose());
        if !pose.finite() {
            return Err("real Skate session returned a non-finite pose".into());
        }
        Ok(pose)
    }

    fn suspend(&mut self) {
        self.accumulated = 0.0;
        if let Some(session) = self.session.as_mut() {
            session.suspend_input();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use api::SessionBackend as _;

    #[test]
    fn missing_data_root_fails_before_session_load() {
        let missing = std::env::temp_dir().join(format!(
            "skycraft-skate-missing-{}",
            std::process::id()
        ));
        let error = RealSkateSession::resolve_data_root(&missing).unwrap_err();
        assert!(error.contains("prepared Skate data is incomplete"));
    }

    #[test]
    fn construction_does_not_touch_retail_data() {
        let adapter = RealSkateSession::new(PathBuf::from("not-present-in-ci"));
        assert!(adapter.session.is_none());
        assert!(adapter.pending_world.is_none());
    }

    #[test]
    fn delayed_world_cannot_replace_newer_pending_revision() {
        let mut adapter = RealSkateSession::new(PathBuf::from("not-present-in-ci"));
        adapter.install_world(api::WorldGeometry { revision: 12, ..Default::default() }).unwrap();
        adapter.install_world(api::WorldGeometry { revision: 11, ..Default::default() }).unwrap();

        assert_eq!(adapter.requested_revision, 12);
        assert_eq!(adapter.pending_world.as_ref().map(|world| world.revision), Some(12));
    }

    #[test]
    fn revision_order_survives_u64_wrap() {
        assert!(RealSkateSession::revision_is_newer(0, u64::MAX));
        assert!(!RealSkateSession::revision_is_newer(u64::MAX, 0));
        assert!(!RealSkateSession::revision_is_newer(7, 7));
    }
}
